version: "3.7"

services:
  tui_api:
    image: tui_test:development
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      NODE_ENV: development
      GIT_HUB_API_KEY: ''
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/node/tui_test/src
      - /home/node/tui_test/node_modules
    networks:
      - tui-network
networks:
  tui-network:
    driver: bridge
